GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2VubmV0aCIsImlhdCI6MTY4NTE2OTYyOCwiZXhwIjoxNjg1MTY5NjQ4fQ.R_uGL9QgZgFXg7ZzY3fxKfLGJAjSqlP8KvbnrPy9Z9Q

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kenneth"
}

###

POST http://localhost:3000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2VubmV0aCIsImlhdCI6MTY4NTE2OTYxN30.2C-UgkwHeXpXx4DNdL6DXTwJS985KufuRONCVmC0AdI"
}

###

//invalidating the refresh token

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2VubmV0aCIsImlhdCI6MTY3MTAxOTAzOH0.lWCGSAXFTR2oAhCIHO24j-b6p_KXmopqTstokbB0nBo"
}
